### ISSUE TITLE
关于论文中BadNet(m)和BadNet（h）的问题

### ISSUE THREAD

**Issue by poang** [thunlp/ONION#2]
请问一下论文中对BadNet(m)和BadNet（h）这两个实验是BadNL这篇论文中提到的**MixUp-based Trigger**和**Thesaurus-based Trigger**这两种生成trigger的方法吗？
如果是的话，您可以将这部分构建的代码开源吗？因为读原论文的时候没有看懂他们是如何构建的。
如果您不想出现在这个repo中，可以发到我的邮箱：poangsdog@gmail.com。

十分感谢！

**Comment by Yangyi-Chen** [comment]
Hello, 感谢关注！
BadNet(m), BadNet(h) 是基于BadNet 插词的下毒方式的改版；
区别是，原[BadNet](https://arxiv.org/abs/2004.06660)使用的是低频词作为trigger， 而BadNet(m), BadNet(h) 分别使用的是中频、高频词。 跟BadNL这篇论文里的方法没必然联系；

**Comment by poang** [comment]
> Hello, 感谢关注！ BadNet(m), BadNet(h) 是基于BadNet 插词的下毒方式的改版； 区别是，原[BadNet](https://arxiv.org/abs/2004.06660)使用的是低频词作为trigger， 而BadNet(m), BadNet(h) 分别使用的是中频、高频词。 跟BadNL这篇论文里的方法没必然联系；

感谢回复，是我的问题，论文中这两种方法后面是BadNL这篇论文的引用，误以为是其中的方法。 ：(

**Comment by Yangyi-Chen** [comment]
😂
